name: schema
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - jupyterlab
  - pyyaml[version='>=4.2b1']
  - yt
  - cmyt
  - more-itertools[version='>=8.4']
  - unyt[version='>=2.8.0']
  - sympy[version='>=1.2']
  - numpy[version='>=1.18.5,<2.0a0']
  - tqdm[version='>=3.4.0']
  - toml[version='>=0.10.2']
  - matplotlib-base[version='!=3.4.2,>=2.0.2,<3.6']
  - cython
